---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: travelo-user
  namespace: travelo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: travelo-reader
  namespace: travelo
rules:
- apiGroups: [""]
  resources:
    - pods
    - services
    - configmaps
  verbs:
    - get
    - list
    - watch