apiVersion: v1
kind: Secret
metadata:
  name: travelo-secret
  namespace: travelo

type: Opaque

data:
  MYSQL_ROOT_PASSWORD: VGFreTEyMzQ1
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: VGFreTEyMzQ1
  rootUser: cm9vdA==
  rootHost: JQ==
  rootPassword: VGFreTEyMzQ1